POST https://localhost:7055/postsale/reservation-change-request
accept: */*
Content-Type: application/json
X-UserId: 91d65b42-1d29-4e0e-87a9-f723106257de

{
  "reservationToChangeId": "a80f0eb6-8a55-48dd-a359-2431be0533fc",
  "changeRequestId": "3d6da0e2-be0e-460e-bcee-723c54f33374",
  "newTravelDate": "2023-11-02"
}